CREATE TYPE status_options AS ENUM ('Submitted',
                            'Phone Interview Scheduled',
                            'Phone Interview Completed',
                            'On Site Interview Scheduled',
                            'On Site Interview Completed',
                            'Hired!',
                            'Not Hired');

CREATE TABLE job_thing_jobs (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER REFERENCES job_thing_users(id) ON DELETE CASCADE NOT NULL,
  status status_options,
  description TEXT NOT NULL,
  date_submitted TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);